language: go

go:
  - 1.6
  - tip

install:
  - go get -v github.com/govend/govend
  - govend -v

# The default script is go test -v ./... which will test everything in the vendor directory.
# Only testing this project.
script:
  - go test -v -short ./apns/...
  - go test -v -short ./fcm/...
